http {
    limit_req_zone $binary_remote_addr zone=limitador:10m rate=10r/s;
    limit_req_status 429;

    upstream api_upstream {
        server api1:3000;
        server api2:3000;
        server api3:3000;
    }

    server {
        listen 80;

        location / {
            limit_req zone=limitador burst=20 nodelay;

            proxy_pass http://api_upstream;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}

events {}
